apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: headlessloadgen
  name: headlessloadgen
spec:
  selector:
    matchLabels:
      app: headlessloadgen
  template:
    metadata:
      labels:
        app: headlessloadgen
    spec:
      containers:
      - name: headlessloadgen
        image: gcr.io/dynatrace-demoability/headlessloadgen:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "900Mi"
            cpu: "700m"
        env:
        - name: EASY_TRADE_ADDRESS
          value: frontendreverseproxy
        - name: EASY_TRADE_PORT
          value: "80"
        - name: NODE_LOG_LEVEL
          value: "debug"
